# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager

class TestUntitled():
  def setup_method(self, method):
    options = Options()
    options.add_argument('--headless')
    options.add_argument('--no-sandbox')
    options.add_argument('--disable-dev-shm-usage')
    self.driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_untitled(self):
    # Test name: Untitled
    # Step # | name | target | value
    # 1 | open | / | 
    self.driver.get("https://www.bazos.cz/")
    # 2 | setWindowSize | 1235x902 | 
    self.driver.set_window_size(1235, 902)
    # 3 | type | id=hledat | hyundai i30
    self.driver.find_element(By.ID, "hledat").send_keys("hyundai i30")
    # 4 | click | id=hlokalita | 
    self.driver.find_element(By.ID, "hlokalita").click()
   
    # 6 | type | id=hlokalita | 66424
    self.driver.find_element(By.ID, "hlokalita").send_keys("66424")
    # 7 | click | name=Submit | 
    self.driver.find_element(By.NAME, "Submit").click()
  
    result = self.driver.find_element(By.CLASS_NAME, "maincontent")
    advertisment = result.find_elements(By.CLASS_NAME, "inzeratynadpis")

    for i in advertisment:
      if "Zobrazeno" in i.text:
        continue
      assert 'hyundai' in i.text.lower()
      #print(i.text)

      